export const NEW_EVENT_REQUEST = "NEW_EVENT_REQUEST";
export const NEW_EVENT_SUCCESS = "NEW_EVENT_SUCCESS";
export const NEW_EVENT_FAIL = "NEW_EVENT_FAIL";
export const NEW_EVENT_RESET = "NEW_EVENT_RESET";

export const ALL_EVENT_REQUEST = "ALL_EVENT_REQUEST";
export const ALL_EVENT_SUCCESS = "ALL_EVENT_SUCCESS";
export const ALL_EVENT_FAIL = "ALL_EVENT_FAIL";

export const SINGLE_EVENT_REQUEST = "SINGLE_EVENT_REQUEST";
export const SINGLE_EVENT_SUCCESS = "SINGLE_EVENT_SUCCESS";
export const SINGLE_EVENT_FAIL = "SINGLE_EVENT_FAIL";

export const EVENT_DELETE_REQUEST = "EVENT_DELETE_REQUEST";
export const EVENT_DELETE_SUCCESS = "EVENT_DELETE_SUCCESS";
export const EVENT_DELETE_FAIL = "EVENT_DELETE_FAIL";
export const EVENT_DELETE_RESET = "EVENT_DELETE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
