export const NEW_GALLERY_REQUEST = "NEW_GALLERY_REQUEST";
export const NEW_GALLERY_SUCCESS = "NEW_GALLERY_SUCCESS";
export const NEW_GALLERY_FAIL = "NEW_GALLERY_FAIL";
export const NEW_GALLERY_RESET = "NEW_GALLERY_RESET";

export const ALL_GALLERY_REQUEST = "ALL_GALLERY_REQUEST";
export const ALL_GALLERY_SUCCESS = "ALL_GALLERY_SUCCESS";
export const ALL_GALLERY_FAIL = "ALL_GALLERY_FAIL";

export const SINGLE_GALLERY_REQUEST = "SINGLE_GALLERY_REQUEST";
export const SINGLE_GALLERY_SUCCESS = "SINGLE_GALLERY_SUCCESS";
export const SINGLE_GALLERY_FAIL = "SINGLE_GALLERY_FAIL";


export const GALLERY_DELETE_REQUEST = "GALLERY_DELETE_REQUEST";
export const GALLERY_DELETE_SUCCESS = "GALLERY_DELETE_SUCCESS";
export const GALLERY_DELETE_FAIL = "GALLERY_DELETE_FAIL";
export const GALLERY_DELETE_RESET = "GALLERY_DELETE_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
